version: 2
jobs:
  build:
    branches:
      ignore:
        - master

    docker:
      # specify the version you desire here
      - image: chinucho/careertrek-hacktoberfest-day-2018.github.io:0.0.2
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn ci:prod
      # deploy!!
      - deploy:
          command: |
            if [ $CIRCLE_BRANCH == 'develop' ]; then
              yarn build
              chmod +x .circleci/setup-github.sh && .circleci/setup-github.sh
            fi